default: &default
 adapter: postgresql
 timeout: 5000
development:
 <<: *default
 pool: 5
 host: localhost
 username: juan
 password: 
 port: 5432
 database: development_tasker
test:
 <<: *default
 pool: 5
 host: localhost
 username: juan
 password: 
 port: 5432
 database: test_tasker
production:
 <<: *default
 database: production_tasker