default: &default
 adapter: postgresql
 timeout: 5000
development:
 <<: *default
 pool: 5
 host: localhost
 username: <%= ENV["POSTGRES_USER"] %>
 password: <%= ENV["POSTGRES_PASSWORD"] %>
 port: 5432
 database: development_tasker
test:
 <<: *default
 pool: 5
 host: localhost
 username: <%= ENV["POSTGRES_USER"] %>
 password: <%= ENV["POSTGRES_PASSWORD"] %>
 port: 5432
 database: test_tasker
production:
 <<: *default
 database: production_tasker